### ISSUE TITLE
never ending "unsupported-server-version-v5.37" popup for all admins worldwide

### ISSUE THREAD

**Issue by Pyroluk** [mattermost/notices#326]
```json
  {
    "id": "unsupported-server-version-v5.37-3",
    "conditions": {
      "audience": "sysadmin",
      "clientType": "all",
      "instanceType": "onprem",
      "serverVersion": ["<7.6"]
    },
    "localizedMessages": {
      "en": {
        "title": "2 Your Mattermost server version is unsupported. Upgrading is required",
        "description": "You are on an unsupported Mattermost server version and it’s time to upgrade! [Read here](https://mattermost.com/blog/why-to-upgrade-mattermost-server/?utm_source=inapp-self-hosted&utm_medium=popup&utm_campaign=notification-why-upgrade-blog&utm_id=nov-notifications&utm_content=notification-why-upgrade-blog) on how we have improved server performance for Mattermost users, as well as why upgrading your Mattermost server ensures that you’re getting the latest new features, security fixes, and bug fixes.",
        "image": "https://raw.githubusercontent.com/mattermost/notices/master/images/server_upgrade.png",
        "actionText": "Upgrade Now",
        "actionParam": "https://docs.mattermost.com/upgrade/upgrading-mattermost-server.html?utm_source=inapp-self-hosted&utm_medium=popup&utm_campaign=notification-upgrade&utm_id=nov-notifications&utm_content=notification-upgrade"
      }
    }
  }
```

`"serverVersion": ["<7.6"]`
This causes all admins around the world to be terrorized to finally upgrade to a non-existing version of the Mattermost server, every single time they open up Mattermost.

**Comment by esethna** [comment]
Hi @Pyroluk, notices seen in production instances are based on the `release` branch in this repo

The notice you're referring to is targeting <v7.1 on the `release` branch. We have found a bug with that notice though that is being fixed today (where it is not being marked as read when expected)

**Comment by esethna** [comment]
https://mattermost.atlassian.net/browse/MM-49337

**Comment by esethna** [comment]
@Pyroluk can I also ask out of curiosity why you are running an unsupported server version? Are there challenges you've faced in upgrading? Our deployment PM, @nab-77 would be very interested in your experience

**Comment by Pyroluk** [comment]
@esethna @nab-77 Thank you for fixing the problem. Since over a year ago, I am running an unofficial ARM build of Mattermost from [here](https://github.com/SmartHoneybee/ubiquitous-memory/releases). Not sure if that was the problem. Besides this bug, which popped up out of nowhere a few weeks ago without changing anything on my side, it ran absolutely flawlessly with great performance on ARM64 using mysql as the backend database. ARM is getting more relevant in the server space by the day. Oracle offers always free ARM64 servers with 4 potent cores and 24GB of RAM to anyone. Seems like there is little to none work needed to officially add ARM support to Mattermost. Hope you guys consider it. Cheers 😊!
